function handleEndOfRound() {
    // ... if (wrongQueue.length > 0) con SweetAlert (Ronda de repaso) ...
    // ... 
    } else {
        // ... SweetAlert de Victoria ...
    }
} // <--- La función termina correctamente aquí.
